В данном примере мы использовали следующие параметры:
Функция потерь: binary_crossentropy. Для задачи бинарной классификации, где у нас есть два класса, это хороший выбор, так как она минимизирует расстояние между предсказанными и истинными значениями.
Оптимизатор: adam. Adam - это адаптивный метод оптимизации, который эффективно обновляет веса модели, учитывая градиенты.
Метрики: accuracy. Метрика accuracy позволяет оценить процент правильно классифицированных примеров на обучающей и тестовой выборках.
Мы обучили модель на 5 эпохах с размером пакета 32 и использовали валидационную выборку для мониторинга процесса обучения.


Когда мы учим нейросетку на рандомных данных, то нет никакой логической зависимости x от y и поэтому нейросетка учится с примерной точностью 50%
Когда на своих возникает переобучение, потому что данных слишком мало. 

В идеале взять какой-то датасет из интернета 

In [54]:
import numpy as np

# Создание синтетического датасета
# np.random.seed(42)
# X = np.random.randn(1000, 2) % 1  # Двумерные признаки
# y = np.random.randint(0, 2, 1000)  # Метки классов (0 или 1)

# Создание датасета руками
X = np.array([[1, 2], [2, 3], [3, 4], [4, 5], [5, 6], [6, 7], [7, 8], [8, 9], [9, 10], [10, 11], [1, 1], [3, 1]])
y = np.array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0])

# Разделение датасета на обучающую и тестовую выборки
split_ratio = 0.6  # Процент данных для обучения
split_index = int(len(X) * split_ratio)

X_train = X[:split_index]
y_train = y[:split_index]
X_test = X[split_index:]
y_test = y[split_index:]

print(X_train,'\n',"===========",'\n', y_train,'\n',"===========",'\n', X_test,'\n',"===========",'\n', y_test)

[[1 2]
 [2 3]
 [3 4]
 [4 5]
 [5 6]
 [6 7]
 [7 8]] 
 [0 0 0 0 1 1 1] 
 [[ 8  9]
 [ 9 10]
 [10 11]
 [ 1  1]
 [ 3  1]] 
 [1 1 1 0 0]


In [17]:
from keras.models import Sequential
from keras.layers import Dense

# Создание модели
model = Sequential()
model.add(Dense(10, input_dim=2, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

# Компиляция модели
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# Обучение модели
model.fit(X_train, y_train, epochs=5, batch_size=32, validation_data=(X_test, y_test))

Epoch 1/5
1/1 [==============================] - 2s 2s/step - loss: 2.2470 - accuracy: 0.4444 - val_loss: 2.0285 - val_accuracy: 0.6667
Epoch 2/5
1/1 [==============================] - 0s 75ms/step - loss: 2.2252 - accuracy: 0.4444 - val_loss: 2.0110 - val_accuracy: 0.6667
Epoch 3/5
1/1 [==============================] - 0s 69ms/step - loss: 2.2035 - accuracy: 0.4444 - val_loss: 1.9935 - val_accuracy: 0.6667
Epoch 4/5
1/1 [==============================] - 0s 69ms/step - loss: 2.1818 - accuracy: 0.4444 - val_loss: 1.9761 - val_accuracy: 0.6667
Epoch 5/5
1/1 [==============================] - 0s 83ms/step - loss: 2.1602 - accuracy: 0.4444 - val_loss: 1.9587 - val_accuracy: 0.6667


Ниже мы загрузили датасет (рак молочной железы) с 30 параметрами и бинарной классификацией

In [31]:
from sklearn.datasets import load_breast_cancer

data = load_breast_cancer()
X_from_lib = data.data
y_from_lib = data.target
print(X_from_lib.shape, y_from_lib.shape)

(569, 30) (569,)


In [61]:
split_ratio = 0.8  # Процент данных для обучения
split_index = int(len(X_from_lib) * split_ratio)

X_from_lib_train = X_from_lib[:split_index]
y_from_lib_train = y_from_lib[:split_index]
X_from_lib_test = X_from_lib[split_index:]
y_from_lib_test = y_from_lib[split_index:]

In [63]:
from keras.models import Sequential
from keras.layers import Dense

# Создание модели
model1 = Sequential()
model1.add(Dense(100, input_dim=30, activation='relu'))
model1.add(Dense(1, activation='sigmoid'))

# Компиляция модели
model1.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# Обучение модели
model1.fit(X_from_lib_train, y_from_lib_train, epochs=10, batch_size=19, validation_data=(X_from_lib_test, y_from_lib_test))

Epoch 1/10
18/18 [==============================] - 2s 27ms/step - loss: 10.4232 - accuracy: 0.2933 - val_loss: 5.3034 - val_accuracy: 0.3772
Epoch 2/10
18/18 [==============================] - 0s 10ms/step - loss: 5.2991 - accuracy: 0.4897 - val_loss: 2.7803 - val_accuracy: 0.6096
Epoch 3/10
18/18 [==============================] - 0s 13ms/step - loss: 2.2278 - accuracy: 0.6628 - val_loss: 1.4348 - val_accuracy: 0.7588
Epoch 4/10
18/18 [==============================] - 0s 10ms/step - loss: 1.5522 - accuracy: 0.7185 - val_loss: 0.7105 - val_accuracy: 0.8728
Epoch 5/10
18/18 [==============================] - 0s 11ms/step - loss: 1.1520 - accuracy: 0.7889 - val_loss: 1.0334 - val_accuracy: 0.8070
Epoch 6/10
18/18 [==============================] - 0s 11ms/step - loss: 0.9505 - accuracy: 0.8152 - val_loss: 0.7643 - val_accuracy: 0.8596
Epoch 7/10
18/18 [==============================] - 0s 10ms/step - loss: 0.8842 - accuracy: 0.8270 - val_loss: 0.8915 - val_accuracy: 0.8289
Epoch 8/10
1